In [ ]:
#Importing all the required libraries.
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
#Loading the dataset into variable data and printing it.
data = pd.read_csv('/content/decision_covid.csv')
print(data)

    Person  AgeGroup  History  AreaPopulated  CasesArea  Covid
0        1         1        0              0          1      0
1        2         2        0              1          1      0
2        3         3        1              1          2      1
3        4         3        1              0          3      1
4        5         2        1              1          2      1
5        6         3        0              0          1      0
6        7         2        0              1          1      0
7        8         2        1              0          3      1
8        9         1        0              1          1      0
9       10         1        0              1          1      0
10      11         1        0              1          2      0
11      12         2        1              1          3      1
12      13         3        0              0          1      0
13      14         3        1              0          2      1
14      15         1        0              1          1

In [ ]:
#Finding the length and shape of the dataset.
print ("Dataset Length: ", len(data))
print ("Dataset Shape: ", data.shape)

Dataset Length:  30
Dataset Shape:  (30, 6)


In [ ]:
#Extracting the input and output from the dataset into variables X and Y.
X = data.values[:, 1:-1]
Y = data.values[:, -1]
Y=Y.astype('int')

In [ ]:
#Splitting the data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)

In [ ]:
#Defining the model with gini criteria.The tree will have a maximum depth of 3 and the minimum number of samples required to be at a leaf node is taken as 3.
#Then training the model on training data.
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=3)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [ ]:
# Predicting the X_test values and storing it in y_pred and displaying it.
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[0 1 0 0 0 0 0 0 0]


In [ ]:
#Confusion matrix of the predictions.
confusion_matrix(y_test, y_pred)

array([[6, 0],
       [2, 1]])

In [ ]:
#Calculating and displaying the accuracy of our model.
accuracy_score(y_test,y_pred)*100

77.77777777777779

In [ ]:
#Testing the model on a sample input value
test= clf_gini.predict([[1,1,1,2]])

In [ ]:
# value in output
test

array([1])

In [ ]:
#Classification report of the model
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         6
           1       1.00      0.33      0.50         3

    accuracy                           0.78         9
   macro avg       0.88      0.67      0.68         9
weighted avg       0.83      0.78      0.74         9

